name: ElysiumAuthPaper
version: 0.1
main: com.skilfully.elysium.elysium_auth.ElysiumAuthPaper
api-version: '1.17'
authors:
    - "Elysium Studio"
description: Elysium Auth for Paper
website: elysium.skilfully.cn
